[package]
name = "helix"
version = "0.1.0"
authors = ["aark"]

[dependencies]
sha2 = "0.7.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
regex = "1.0.2"
hex = "0.3.2"
data-encoding = "2.1.1"
